Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 40
  ExcludedMethods: ['describe', 'context', 'namespace', 'task']

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: predicate

Style/SymbolArray:
  Enabled: false

AllCops:
  Exclude:
    - config/**/*
    - db/**/*
    - bin/*
    - script/*
    - lib/tasks/cucumber.rake
    - features/support/env.rb
    - vendor/**/*
