Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 40
  IgnoredMethods: ['describe', 'context', 'namespace', 'task']

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: predicate

Style/SymbolArray:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 100

Lint/MissingCopEnableDirective:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - features/support/env.rb
    - lib/tasks/cucumber.rake
    - script/*
    - vendor/bundle/**/*
