language: ruby
cache:
  bundler: true
rvm:
  - rvm 2.6.3
services:
  - postgresql
addons:
  postgresql: "9.5"

script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rails db:create db:schema:load --trace
  - bundle exec rspec
  - bundle exec cucumber

deploy:
  provider: heroku
  api_key:
    secure: pEvjGce2ZsjAJgTLM/tavsilQjE9Drw/eAAfNdT9OKdSxE18mbYMAZgET/+PDcCaePgTAAiqPN05D1JlOTKilDgNWaCQDp1w0InSz7LCBhIH1PyTpIR53bMVJYmbeagSWEhK9Q5wocPP/a1dsQU5sahr28EI5NEX8nFoO19A1W2SUoerwh+OG6XM5aXvcQBvDN/ZV1flXhVEI0ZOFDsS3SC2QUoPBpo3miKN5AybiADAkMgYsn5pBKiTFTqsP/5gqzAY8Ik8U+4tTeySVOIndJxZ8SfjQHXGwgbvzEcphKLzoru2FfUthKpWmq3vZYqDyVmoNFPk2DJ9wMUwv+eP7BNMY72+TQ2INOYNXsWuoMbbBzfaEXzO4SeA6bZpJPx/VDu5FIwd3DP71u5WwxeUpAOeG4cbtx+3msPPMlOms+CPrl4jkn9poOoNzCfiGDeYOdjngt8Ip7TeVm51Qx1yYOGVm17CwL7RY/w9V90zyxMGAV6l/A/WeQlU+a6HvoiZTlwXsZHjkMIYqnS/PA1+KtYhh7OxUxQwZDRQSQ0x+69R8andyGk98Q/2kZ1VRKlB4G0P3KP7D2Jxhr1se4Mb315WNHY4AHE3EddblbiAJ71jSvO8wsoyrE0R7rJSU4IbT1G6Cxn4jgbo/NQSbZugsbNLVTl6uWk4mDbWPoMX2AM=
  run: bundle exec rake db:migrate
  skip_cleanup: true
  on:
    branch:
      - master
