language: ruby
cache: bundler
rvm:
  - rvm 2.6.3
services:
  - postgresql
addons:
  postgresql: "9.5"

script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rails db:create db:migrate

deploy:
  provider: heroku
  api_key:
    secure: bznq4xKEHmIUT7E3vB5Sdlbyvq3QjKYarzWvqeNh34Z4fHbWkKrgDY9RwGGu+8SQH5yArVK7UIn1h9MlpScym80/2/G5uGkOlcqa2ymuUJwJFTirpURGvuL64DzNTwG6tpjL+E9Em0xiHAvO91D/agCrUoZ9r+sjPx5m4nAnPn/k9amv8Eyfyea0FAWPSVComCXo6ngvhQlnhtPTNOQJHjPQi6DRe2bOLyJPHF1cibCHLonwsONMOLJ/PO0k27LNH8aVwKnOnENTN/Xzjg1v0gBoEDthdpB7u/en7pqhcO8U6TpZCfNZVgIjyEu2rvjkDaXdsxVKNQGOUK7nTuwCiPDoSme1XOl4vsIiHjWWUBonu0bJh0KcEfbrXWajn0tU1W4BlIBdC9Gf1kIJW/UdCbq0iInPsKi9WxYc3G+QlJf6ToFozOYIh8bw5hSWF6DYb6CPYOewlMPB+zWbuTPxNL5HRyEyW4kARR392pvu5NylnlZp44ShXoldRK35rV2X/J1WH0wqSQU+dkIuGGwiNFgies4Tt7zI+EIx2BzBmohmlZtuhVj50Fo6NffZF8P2KZTY30BnCTA4TXg/drIoZidtaip0i2+kV0xOaxumVIVbIK2ZrQx/EuZ1UX3Y36jTfydXr8XxH63xSpnvKBBVMoJFB5tEg0d+xBCaIN2FDQI=
  run: bundle exec rake db:migrate
  skip_cleanup: true
  on:
    branch: master
