dist: bionic
language: ruby
cache:
  bundler: true
rvm:
  - rvm 2.7.4
services:
  - postgresql
addons:
  postgresql: "9.5"

script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rails db:create db:schema:load --trace
  - bundle exec rspec
  - bundle exec cucumber

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.10.0

deploy:
  provider: heroku
  api_key:
    secure: OWLs1k5vBJ2GLog5bkHMwvPZSVIpRGq77B+Fx4F2PC/e6y2g+Djh1MG70sCo/Vjc1K33VGo0OWXGWr6jveV500wXXKE+0CgtOkEWqM4/eK/5M0h1cFP8G2xmXbtY4RDY6l1bIcPG1U3hr5y6TJn9NUqiwSybAfcor445issbCBJZHYu4dxseDfy92VTRhr6VsnukrH6NtpekHSP1B1HjZNze/EpZVM57g4NHRsfrNMe1OXi2Fu0AsWzY5qBdOesyC8DORb3R174wO1sGHpmaz7q1p6XT+PUcEL6A91eAq1lnR+8lyiGhU3hZL6ZWACYdkwbtCtawivWiWCk/nbYU/IjfSFmhErqLTWlm3WXgkGXNxTqjxFymN/MkXIK4Ni3l7CgxGpWODXaxW7nC5GQR1Qq4EeLttjl43VekwrXfB/cu8QzEt28rkNAVSI45kLWq9H+vl8GREqX8SJrnMs3KBNvlEVClqjnrZf2ebwVuzTgRtU974QpHpk0wmxBjbCkRXgeAWQUbOlpK4QYA7ZT2SkBoXO0k2B/xarOW/PmO4EJryQmahBLTYlclKsybWH1E1951rF/4WjDk//+pB93tSIE1aw2dqy3Fzr8gnaaecplnigCcUpFpzvuzNz2DLqqli7Hje9Bo5UTw3zbuPBLt2r8/OllTnv4yBBEXfaIou3g=

  run: bundle exec rake db:migrate
  skip_cleanup: true
  on:
    branch:
      - main
