language: ruby
cache:
  bundler: true
rvm:
  - rvm 2.6.3
services:
  - postgresql
addons:
  postgresql: "9.5"

script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rails db:create db:schema:load --trace
  - bundle exec rspec
  - bundle exec cucumber

deploy:
  provider: heroku
  api_key:
    secure: p4kz6VYegmMlYHNMacuTMYIKB2HhiQH7NaUbjYhVPD4I0nHDeVHE0+agswsouHmHrHIUjeM5rGlqqWgr3RMAMwqwh8OkHqE7pq3S2YKEKcdCF0XM7mMUaGuOQdDR9jTe0dXPOO0+OE4B+pJosDAxyuoPxH4XSZ+JQtZ5JNVc8p9OAXULmFmIdv9zAlNCSzOe/Wcz1jZmMevLGGuyURN0srsRhRkZ8+pL59XndKpIRenIqjzjdi9nTpE2ozT9RS2geeA2WGhg5CtiO0o6YW69oH8C5Gw8DO14QZ98MFnXkZGWg6i74P1a1uzapNnUm+VgPmIvqOaEdyy6hraomZqq+GReSWH5Ml3HGGuBh31ACluOOuB++dARwr+7B6WSxufwUHdXDDmNMok3fPHy6u1yo6R7BiFQqa+rJdJvjBmKVCSCMdq+QNeh3auyz4woY5nCuL4sAS2nBG8S7WtGvbbJC/lmNLkacHJC3TXxsLYX0y+FwNEP3RIX+J9bfpzQx+zPgIh2QAXvUqtZOfIg43vrBiOXSw1zHORXNXVq13KFAlCorowHNP9JPv75LZ1De68oOkALUe2YbFl8pZA2kCe5pVtYW7zGDc1oWh2YlTLCOWKx3TFtCT29LmJNQ/BxjWuiQMNiMOPSwbyyvHTLFnFd6SOfwUfkCIFYtSQ93gObby0=

  run: bundle exec rake db:migrate
  skip_cleanup: true
  on:
    branch:
      - master
