language: ruby
cache:
  bundler: true
rvm:
  - rvm 2.6.3
services:
  - postgresql
addons:
  postgresql: "9.5"

script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rails db:create db:schema:load --trace
  - bundle exec rspec
  - bundle exec cucumber

deploy:
  provider: heroku
  api_key:
    secure: Fwn8VQDjBiUA+LdkdX9FSVLFByD0IuY3esp5EOLerh1UO0MUgiKpRGs287JYto1s75oAsSdYhkhFkME3pcqX/YtBGudpHXAdZqQ4i741pogvEqtDmZRQOW+AdftTsMyfllkj/kN8+acWAleBtf0DvtV7tWBrtTp8/XYbaMnrLPkVXqF0TorUSoFR3mrUBcqM7HsSIgOhLX6R73XkqOwcDQBEyiqczM5CAM9378zsqpGfe6gLZmPzL6g1VC4tVTwgnp08ZCRqWvuCNcdGyJ+aFC+ACRyKUr1omhOz/4Kmp6ftLFnAPbhMJeH7QqUhTAj9Mf9TvLjgQ15LUx8JQ5r4HBVCmMY08IKnc82g6+Gl9J7WmnA5cN6BG/ppVT5HAZSy0ClgFC67bChXSfVzbU4AUpPPwp5PazqxwHzj6wRw2BRVfvwMwvrNM2k6QRq/dyHL3Xzoc+D8HgWG1JmNCjJtKPTkl9STnj4wSWjnThDbOd/4yzIORy6yMYkLubCMAJqDIPAwyu/fS9sBUsNrsDT9tiqDY7sXshsNW6myH/4aSHoUdd7i7L1dPcw4o0YEUxLVYhOZDnRhxg59NsICBw+7qkRYD7dZJPHgkbkw8JcC3oiPfoyJtv2pZKkh2Bp1hA6Z1VKDn22v8kWKKKZJpCJdA1reVIMSQ3SkbwDjLWRqZK8=

  run: bundle exec rake db:migrate
  skip_cleanup: true
  on:
    branch:
      - master
