language: ruby
cache: bundler
rvm:
  - rvm 2.6.3

before_script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rails db:create db:migrate

deploy:
  provider: heroku
  api_key:
    secure: bJKUs3cnB9rIOOn2W3PYGUIYDtO72pXLxZAVScB3AAym3YGcAqA3N1QX3XUH0q1OeziAOE5wAoVNQrr1PrGKHzszRxantk+DqA6iiw2/ZWKr5MmKEOHwvu3y+byjZqDlFGeSD4CtRo7qw+E9Z584z9wh+jvk77/IjCFfV2KbkukxKU0zspdgtITJjX6/bTYEljBLjGJzGCaBvM50LNNVjtfH5eqkZ2AXXhHX0pf4NrwOdCHMl/x/cHfmLnFV3E5iofXNioqERg6Drk6Z6R0LFtUMpSRzZ4sr/DIB/xS8aOXLqI21jm5ch6CixUDfxWUgnXu4OcotC0aRiRWhkh1zwOP2IJoBz01Fzd30o8BKgzETC/uhDCOr3e0W9hasnbeapWAobq1U2zBA0Z32P/y3yQ8umhI7L4UGNhdUVfdXliEIgL9dhRHpGRvGtTdfZPWTXgujSrvOoVppxnJpancl8wNzr67Aoam6YaJR0io6UvqOoRgLxe5wyu0Zrj4VOUMTieaR8SQuNj/NeSH70PaWKfw2IZZIJO2vzZo5rmRiRRyAnCC7aaxMsaLyCSyGQvsRfFu4/LuCXABcCva8UfR0xSFdJ8wPB6PlUA5PdB8FHdmiqiliinmQfc3uJ3PphYeGjsmqDVNcRYexd2jyE6reLelbWzRfbtzM5iRTdOAT2Qc=
  run: bundle exec rake db:migrate
  skip_cleanup: true
  on:
    branch: master
