dist: bionic
language: ruby
cache:
  bundler: true
rvm:
  - rvm 2.7.4
services:
  - postgresql
addons:
  postgresql: "9.5"

script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rails db:create db:schema:load --trace
  - bundle exec rspec
  - bundle exec cucumber

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.10.0

deploy:
  provider: heroku
  api_key:
    secure: syUmkvs1u2zq7YWfz2TFMzvdx7+xTzu8srD9Febx4bgOcVF84DzquiHt0pk1QiePnShkMfNTbWlG/HOKSvlpNzLus9+E8VdN59DJ8h1rwle9sUUcMmpnNFZNwgmiR2mFndJoDxAPZpI79IBFzqVUs08x7puTJNSUceg3hSkxNoCv+BZ3jrzPE2HuG9IaVc8MIs3Y6jOuj72mEsASBHRm3Qk8+QJoPN4PAnVIf2YT2knXm9uhIYvLWqTAOYhbe1uEDg3uM8IhgPy4JksJcvFsSwS2M36cg0hLQGCAyG0cP/trwvqymQAJrIhbqYqu6tGGtpD21fdXreWyEQRtunCnbQajbrbANJ7zX0/bKKCTHnWLesErlmjfGRnx18Zxvg7h5utmisg+xkFPhgAlogmaCWr68/n6P4J+6QYGlMrsii2Ya9uPgqub3lOx1IejPQyBj6Gv6O2XMIiB2JYwGDg9PHEN/luaDsCOMAIjS+mBxHUkFz7/0DI5fjz6SpUlEJahpOwdpndl29TeoJqi4AXP8CINRXs3qH2RjsHyktOjOGB49AJKHOraN3ep+VmZYv53GyIpI0F1xnYWBbxGBtfw7i/iiSkHxxoJhZNwGJy//8RXSAxNPdQ4e4n1g91UU34xlLLR8djNxr0WMetlMdMr+1EKP7IWU9b8nfEdSnjL/ls=

  run: bundle exec rake db:migrate
  skip_cleanup: true
  on:
    branch:
      - main
