language: ruby
rvm:
  - rvm 2.3.1

before_script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rake db:create db:migrate

deploy:
  provider: heroku
  api_key:
    secure: pZ3mzTIw+nOnINsNCUsxvYDUbk+p8ZXrCsr+pjWep3HPLILuLdHTkw+xlzyTATTQYphP1YJ3GNy2/2ui+0eqCl6CcyPNAG3GNQLVJJG1x+TPHbfQ28dS+op5+XiddO17RE7yGG097Qb6deY9sV5zaUPssRx2hu1xQU+nc4QrIideKwwdpcusGm/ePl5exWXJiQL1CLV0boNkDEmeoNsuYm+WgUK2k62Afl8AxdQIxHVYt0FwwYPwfUrOqNjG8XEUkzHQ3m6VnFBr+w2mT7XZnDPbWBRSi+WzNfZgeiyhmwQVRszUUjysmmUbC7cfyBzxWtuRvMvbnwIfGQ6QvXllMtpGZofveY0eaXRI3BSjD3IWjTAd5zA4oDj1Wx30Q1wMIGZd4Ml94mwagiHJg+zh54AcdsHtQ+o7jHS9t5B5SdKSVeYWcJDDq6k5ogWF5n2K/WoznY2mViFgS6V+1MVMoioVQ/hRlF5znOiGIddb/HTRnc7smnIOtR+Ym9Fyw4FA3NcRgB/kaKfWxVOza4xdLtcnUjSylm/UZkJv1ns71Bxy7nGNsWpFQRbWRZu14w9qfbk2pmtsy9+AtLLUadqHWBo2j0Ks8NKUczHoCDXmk4mew8X7FBjZaaLXrk56+wu0h9SHaEFHgBwxr8G9W8XE9DCyCnOADvBeUmAQCh1jcUY=
  run: "bundle exec rake db:migrate"
  skip_cleanup: true
