dist: bionic
language: ruby
cache:
  bundler: true
rvm:
  - rvm 2.7.4
services:
  - postgresql
addons:
  postgresql: "9.5"

script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rails db:create db:schema:load --trace
  - bundle exec rspec
  - bundle exec cucumber

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.10.0

deploy:
  provider: heroku
  api_key:
    secure: Y8ibNagB4eYPElj3B50xV9dwlk4I1g3DMFIJ0vDrK9vthU9mYdl6K7fYVWLc2OtAQGaQ2PisVJi4FqildeZhmIEs/25Cuhfhj/75hnWPRIWjliJVUu82pycO+9diFcC+uD7r41GC6yihzwU2yce+LSo2uOn+OnFXSm1wABlRkZMbfk/IEX2wlNgJ0ZCPzu/ym4qiGEiJAWT94uJXBTZZg/lZq+sMHbg/iZNHc1ERmq1TTaKF20QfZlWEw5EqyuGgJxt+PQsYy1Q3zjE5Zo+85svATYFNvei28HROCjKad3HVkQ5a/NgcG4Y2TTPc2KvJg+w57M7eqgFX485V1Bb9a5W7+rwSxYU231UJGKj43i4EEL07DxXjcEUWeboQDwGjBL1UcAu3UNbnJ4zsoYaNnQKlwGtiTO/IEBmUYN0m/58fRo91MF4nx7aoTsXAKpwHk5DudHYCj5doxmxkbuHC+BsNUp0fSD9D4VPmzABt9OXMW7+W+NfFQCEGKUTnFGCTNQ0XMM8DyslLlfd3luW/OqGvRG6nLvhziK9XjjotrVL8+otrxxZKfbTDkVP7HlRusZm1L1xLWpqu/QPghRHHEM0PflqETJjgwFGzlIo99evSZdaZE4oINonehwnlbtpDoeYUqJIIppBuySHgkpGYLDZahlcEE65wCCsnYlr6t6c=

  run: bundle exec rake db:migrate
  skip_cleanup: true
  on:
    branch:
      - main
