common_env: &common_env
  aws:
    bucket:            <%= ENV.fetch('AWS_BUCKET') %>
    access_key_id:     <%= ENV.fetch('AWS_ACCESS_KEY_ID') %>
    secret_access_key: <%= ENV.fetch('AWS_SECRET_ACCESS_KEY') %>

development:
  <<: *common_env
  secret_key_base: d4cbaba75729e1bce597804686e5499f3c1068eddfdf28d8a82a1cbb5e3de55084da2ca5bca234e24c7d29c57e172251a2057fc1a8a21c6d16ca8582a0534f86

test:
  <<: *common_env
  secret_key_base: 38e67e8d53367b44226dbe8c870239de6ddef565534f771b836d4fe5bca534940f56bfd191bed2c842b82ed14b2c7defdb03a61ddc31b8dc55b36df6dd1896be

production:
  <<: *common_env
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>
  redis_url:       <%= ENV.fetch('REDIS_URL') %>
