name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    services:
      postgres:
        image: postgres:9.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Prepare database
        run: bundle exec rails db:create db:schema:load --trace
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/hippocrates_test"

      - name: Run RSpec
        run: bundle exec rspec
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/hippocrates_test"

      - name: Run Cucumber
        run: bundle exec cucumber
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/hippocrates_test"

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: hippocrates
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          run: rake db:migrate
        if: github.ref == 'refs/heads/main'
